name: Build using Cake.Sdk and File based Cake
on:
  push:
    branches:
      - develop
      - main
  pull_request:
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK (global.json)
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Run Cake File
        uses: cake-build/cake-action@3.0.1
        with:
          file-path: cake.cs
          target: GitHubActions